

package dev.rnett.spekt.auto.implementation.compile;

import com.intellij.testFramework.TestDataPath;
import dev.rnett.kcp.development.testing.generation.configuration.ConfigurationHost;
import dev.rnett.kcp.development.testing.tests.levels.AbstractLeveledIrTest;
import dev.rnett.kcp.development.testing.tests.levels.TestLevel;
import dev.rnett.kcp.development.testing.tests.levels.TestWithLevel;
import dev.rnett.spekt.TestGenerator;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.test.builders.TestConfigurationBuilder;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/**
 * This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerationBootstrapper}. DO NOT MODIFY MANUALLY
 */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/implementation/compile")
@TestDataPath("$PROJECT_ROOT")
@TestWithLevel(level = TestLevel.Diagnostics)
@TestWithLevel(level = TestLevel.FIR)
@TestWithLevel(level = TestLevel.IR)
public class ImplementationCompileTestGenerated extends AbstractLeveledIrTest {
    @Override
    public void configure(TestConfigurationBuilder builder) {
        super.configure(builder);
        ConfigurationHost.applyRuntimeConfiguration(this, builder, TestGenerator.class);
    }

    @Test
    public void testAllFilesPresentInCompile() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/implementation/compile"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("Basic.kt")
    public void testBasic() {
        runTest("src/testData/auto/implementation/compile/Basic.kt");
    }
}
