

package dev.rnett.inspekt.auto.inspekt.box;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import dev.rnett.kcp.development.testing.tests.levels.TestWithLevel;
import dev.rnett.kcp.development.testing.tests.levels.TestLevel;
import dev.rnett.inspekt.TestGenerator;
import dev.rnett.kcp.development.testing.generation.configuration.ConfigurationHost;
import org.jetbrains.kotlin.test.builders.TestConfigurationBuilder;
import dev.rnett.kcp.development.testing.tests.levels.AbstractLeveledBoxTest;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerationBootstrapper}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/inspekt/box")
@TestDataPath("$PROJECT_ROOT")
@TestWithLevel(level = TestLevel.Diagnostics)
@TestWithLevel(level = TestLevel.FIR)
@TestWithLevel(level = TestLevel.IR)
@TestWithLevel(level = TestLevel.Run)
public class InspektBoxTestGenerated extends AbstractLeveledBoxTest {
  @Override
  public void configure(TestConfigurationBuilder builder) {
    super.configure(builder);
    ConfigurationHost.applyRuntimeConfiguration(this, builder, TestGenerator.class);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/inspekt/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("Class.kt")
  public void testClass() {
    runTest("src/testData/auto/inspekt/box/Class.kt");
  }

  @Test
  @TestMetadata("ClassExternal.kt")
  public void testClassExternal() {
    runTest("src/testData/auto/inspekt/box/ClassExternal.kt");
  }

  @Test
  @TestMetadata("Function.kt")
  public void testFunction() {
    runTest("src/testData/auto/inspekt/box/Function.kt");
  }

  @Test
  @TestMetadata("FunctionExternal.kt")
  public void testFunctionExternal() {
    runTest("src/testData/auto/inspekt/box/FunctionExternal.kt");
  }

  @Test
  @TestMetadata("Property.kt")
  public void testProperty() {
    runTest("src/testData/auto/inspekt/box/Property.kt");
  }

  @Test
  @TestMetadata("PropertyExternal.kt")
  public void testPropertyExternal() {
    runTest("src/testData/auto/inspekt/box/PropertyExternal.kt");
  }
}
