

package dev.rnett.inspekt.auto.proxy.box;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import dev.rnett.kcp.development.testing.tests.levels.TestWithLevel;
import dev.rnett.kcp.development.testing.tests.levels.TestLevel;
import dev.rnett.inspekt.TestGenerator;
import dev.rnett.kcp.development.testing.generation.configuration.ConfigurationHost;
import org.jetbrains.kotlin.test.builders.NonGroupingPhaseTestConfigurationBuilder;
import dev.rnett.kcp.development.testing.tests.levels.AbstractLeveledBoxTest;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerationBootstrapper}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/proxy/box")
@TestDataPath("$PROJECT_ROOT")
@TestWithLevel(level = TestLevel.Diagnostics)
@TestWithLevel(level = TestLevel.FIR)
@TestWithLevel(level = TestLevel.IR)
@TestWithLevel(level = TestLevel.Run)
public class ProxyBoxTestGenerated extends AbstractLeveledBoxTest {
  @Override
  public void configure(NonGroupingPhaseTestConfigurationBuilder builder) {
    super.configure(builder);
    ConfigurationHost.applyRuntimeConfiguration(this, builder, TestGenerator.class);
  }

  private void run(String fileName) {
    runTest("src/testData/auto/proxy/box/" + fileName);
  }

  @Test
  @TestMetadata("AddedSetterProxy.kt")
  public void testAddedSetterProxy() {
    run("AddedSetterProxy.kt");
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/proxy/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("BasicProxy.kt")
  public void testBasicProxy() {
    run("BasicProxy.kt");
  }

  @Test
  @TestMetadata("DefaultArgsProxy.kt")
  public void testDefaultArgsProxy() {
    run("DefaultArgsProxy.kt");
  }

  @Test
  @TestMetadata("IntermediateOverrideProxy.kt")
  public void testIntermediateOverrideProxy() {
    run("IntermediateOverrideProxy.kt");
  }

  @Test
  @TestMetadata("IntermediateSetterProxy.kt")
  public void testIntermediateSetterProxy() {
    run("IntermediateSetterProxy.kt");
  }

  @Test
  @TestMetadata("ProxyFactory.kt")
  public void testProxyFactory() {
    run("ProxyFactory.kt");
  }

  @Test
  @TestMetadata("ProxyWithDefault.kt")
  public void testProxyWithDefault() {
    run("ProxyWithDefault.kt");
  }

  @Test
  @TestMetadata("ProxyableSpekt.kt")
  public void testProxyableSpekt() {
    run("ProxyableSpekt.kt");
  }

  @Test
  @TestMetadata("SuspendProxy.kt")
  public void testSuspendProxy() {
    run("SuspendProxy.kt");
  }
}
