

package dev.rnett.inspekt.auto.proxy.compile;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import dev.rnett.kcp.development.testing.tests.levels.TestWithLevel;
import dev.rnett.kcp.development.testing.tests.levels.TestLevel;
import dev.rnett.inspekt.TestGenerator;
import dev.rnett.kcp.development.testing.generation.configuration.ConfigurationHost;
import org.jetbrains.kotlin.test.builders.TestConfigurationBuilder;
import dev.rnett.kcp.development.testing.tests.levels.AbstractLeveledIrTest;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerationBootstrapper}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/proxy/compile")
@TestDataPath("$PROJECT_ROOT")
@TestWithLevel(level = TestLevel.Diagnostics)
@TestWithLevel(level = TestLevel.FIR)
@TestWithLevel(level = TestLevel.IR)
public class ProxyCompileTestGenerated extends AbstractLeveledIrTest {
  @Override
  public void configure(TestConfigurationBuilder builder) {
    super.configure(builder);
    ConfigurationHost.applyRuntimeConfiguration(this, builder, TestGenerator.class);
  }

  @Test
  public void testAllFilesPresentInCompile() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/proxy/compile"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("ConflictProxy.kt")
  public void testConflictProxy() {
    runTest("src/testData/auto/proxy/compile/ConflictProxy.kt");
  }
}
