

package dev.rnett.inspekt.auto.diagnostics;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import dev.rnett.kcp.development.testing.tests.levels.TestWithLevel;
import dev.rnett.kcp.development.testing.tests.levels.TestLevel;
import dev.rnett.inspekt.TestGenerator;
import dev.rnett.kcp.development.testing.generation.configuration.ConfigurationHost;
import org.jetbrains.kotlin.test.builders.TestConfigurationBuilder;
import dev.rnett.kcp.development.testing.tests.levels.AbstractLeveledFirTest;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerationBootstrapper}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/diagnostics")
@TestDataPath("$PROJECT_ROOT")
@TestWithLevel(level = TestLevel.Diagnostics)
public class AutoDiagnosticsTestGenerated extends AbstractLeveledFirTest {
  @Override
  public void configure(TestConfigurationBuilder builder) {
    super.configure(builder);
    ConfigurationHost.applyRuntimeConfiguration(this, builder, TestGenerator.class);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("src/testData/auto/diagnostics/defaults")
  @TestDataPath("$PROJECT_ROOT")
  @TestWithLevel(level = TestLevel.Diagnostics)
  public class Defaults {
    @Test
    public void testAllFilesPresentInDefaults() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/diagnostics/defaults"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("Defaults.kt")
    public void testDefaults() {
      runTest("src/testData/auto/diagnostics/defaults/Defaults.kt");
    }
  }

  @Nested
  @TestMetadata("src/testData/auto/diagnostics/references")
  @TestDataPath("$PROJECT_ROOT")
  @TestWithLevel(level = TestLevel.Diagnostics)
  public class References {
    @Test
    public void testAllFilesPresentInReferences() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/diagnostics/references"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("Inspekt.kt")
    public void testInspekt() {
      runTest("src/testData/auto/diagnostics/references/Inspekt.kt");
    }

    @Test
    @TestMetadata("Proxy.kt")
    public void testProxy() {
      runTest("src/testData/auto/diagnostics/references/Proxy.kt");
    }
  }
}
