

package dev.rnett.inspekt.auto.implementation.box;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import dev.rnett.kcp.development.testing.tests.levels.TestWithLevel;
import dev.rnett.kcp.development.testing.tests.levels.TestLevel;
import dev.rnett.inspekt.TestGenerator;
import dev.rnett.kcp.development.testing.generation.configuration.ConfigurationHost;
import org.jetbrains.kotlin.test.builders.TestConfigurationBuilder;
import dev.rnett.kcp.development.testing.tests.levels.AbstractLeveledBoxTest;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerationBootstrapper}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/implementation/box")
@TestDataPath("$PROJECT_ROOT")
@TestWithLevel(level = TestLevel.Diagnostics)
@TestWithLevel(level = TestLevel.FIR)
@TestWithLevel(level = TestLevel.IR)
@TestWithLevel(level = TestLevel.Run)
public class ImplementationBoxTestGenerated extends AbstractLeveledBoxTest {
  @Override
  public void configure(TestConfigurationBuilder builder) {
    super.configure(builder);
    ConfigurationHost.applyRuntimeConfiguration(this, builder, TestGenerator.class);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/implementation/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("AnnotationsTest.kt")
  public void testAnnotationsTest() {
    runTest("src/testData/auto/implementation/box/AnnotationsTest.kt");
  }

  @Test
  @TestMetadata("Basic.kt")
  public void testBasic() {
    runTest("src/testData/auto/implementation/box/Basic.kt");
  }

  @Test
  @TestMetadata("Inheritance.kt")
  public void testInheritance() {
    runTest("src/testData/auto/implementation/box/Inheritance.kt");
  }

  @Test
  @TestMetadata("Objects.kt")
  public void testObjects() {
    runTest("src/testData/auto/implementation/box/Objects.kt");
  }

  @Test
  @TestMetadata("Properties.kt")
  public void testProperties() {
    runTest("src/testData/auto/implementation/box/Properties.kt");
  }

  @Test
  @TestMetadata("Sealed.kt")
  public void testSealed() {
    runTest("src/testData/auto/implementation/box/Sealed.kt");
  }

  @Nested
  @TestMetadata("src/testData/auto/implementation/box/invoke")
  @TestDataPath("$PROJECT_ROOT")
  @TestWithLevel(level = TestLevel.Diagnostics)
  @TestWithLevel(level = TestLevel.FIR)
  @TestWithLevel(level = TestLevel.IR)
  @TestWithLevel(level = TestLevel.Run)
  public class Invoke {
    @Test
    public void testAllFilesPresentInInvoke() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/implementation/box/invoke"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ComplexParameters.kt")
    public void testComplexParameters() {
      runTest("src/testData/auto/implementation/box/invoke/ComplexParameters.kt");
    }

    @Test
    @TestMetadata("DefaultArgs.kt")
    public void testDefaultArgs() {
      runTest("src/testData/auto/implementation/box/invoke/DefaultArgs.kt");
    }

    @Test
    @TestMetadata("DependentDefaultArgs.kt")
    public void testDependentDefaultArgs() {
      runTest("src/testData/auto/implementation/box/invoke/DependentDefaultArgs.kt");
    }

    @Test
    @TestMetadata("Inline.kt")
    public void testInline() {
      runTest("src/testData/auto/implementation/box/invoke/Inline.kt");
    }

    @Test
    @TestMetadata("Suspend.kt")
    public void testSuspend() {
      runTest("src/testData/auto/implementation/box/invoke/Suspend.kt");
    }
  }

  @Nested
  @TestMetadata("src/testData/auto/implementation/box/typeparams")
  @TestDataPath("$PROJECT_ROOT")
  @TestWithLevel(level = TestLevel.Diagnostics)
  @TestWithLevel(level = TestLevel.FIR)
  @TestWithLevel(level = TestLevel.IR)
  @TestWithLevel(level = TestLevel.Run)
  public class Typeparams {
    @Test
    public void testAllFilesPresentInTypeparams() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/implementation/box/typeparams"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("FunctionTypeParameters.kt")
    public void testFunctionTypeParameters() {
      runTest("src/testData/auto/implementation/box/typeparams/FunctionTypeParameters.kt");
    }

    @Test
    @TestMetadata("TypeParameterInterdependencies.kt")
    public void testTypeParameterInterdependencies() {
      runTest("src/testData/auto/implementation/box/typeparams/TypeParameterInterdependencies.kt");
    }

    @Test
    @TestMetadata("TypeParameterUpperBounds.kt")
    public void testTypeParameterUpperBounds() {
      runTest("src/testData/auto/implementation/box/typeparams/TypeParameterUpperBounds.kt");
    }

    @Test
    @TestMetadata("TypeParameterVariance.kt")
    public void testTypeParameterVariance() {
      runTest("src/testData/auto/implementation/box/typeparams/TypeParameterVariance.kt");
    }

    @Test
    @TestMetadata("TypeParameters.kt")
    public void testTypeParameters() {
      runTest("src/testData/auto/implementation/box/typeparams/TypeParameters.kt");
    }
  }
}
