

package dev.rnett.spekt.auto.spekt_method.fir;

import com.intellij.testFramework.TestDataPath;
import dev.rnett.kcp.development.testing.generation.configuration.ConfigurationHost;
import dev.rnett.kcp.development.testing.tests.levels.AbstractLeveledFirTest;
import dev.rnett.kcp.development.testing.tests.levels.TestLevel;
import dev.rnett.kcp.development.testing.tests.levels.TestWithLevel;
import dev.rnett.spekt.TestGenerator;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.test.builders.TestConfigurationBuilder;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/**
 * This class is generated by {@link dev.rnett.kcp.development.testing.generation.TestGenerationBootstrapper}. DO NOT MODIFY MANUALLY
 */
@SuppressWarnings("all")
@TestMetadata("src/testData/auto/spekt_method/fir")
@TestDataPath("$PROJECT_ROOT")
@TestWithLevel(level = TestLevel.FIR)
public class Spekt_methodFirTestGenerated extends AbstractLeveledFirTest {
    @Override
    public void configure(TestConfigurationBuilder builder) {
        super.configure(builder);
        ConfigurationHost.applyRuntimeConfiguration(this, builder, TestGenerator.class);
    }

    @Test
    public void testAllFilesPresentInFir() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/auto/spekt_method/fir"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("Basic.kt")
    public void testBasic() {
        runTest("src/testData/auto/spekt_method/fir/Basic.kt");
    }

    @Test
    @TestMetadata("WithCompanion.kt")
    public void testWithCompanion() {
        runTest("src/testData/auto/spekt_method/fir/WithCompanion.kt");
    }

    @Test
    @TestMetadata("WithNamedCompanion.kt")
    public void testWithNamedCompanion() {
        runTest("src/testData/auto/spekt_method/fir/WithNamedCompanion.kt");
    }
}
